import numpy as np

REACTION_TIME = 0.1 # s   # TAU # 0.1-0.5 for humans
MAX_HEADING_ANGLE = np.pi/4
MIN_HEADING_ANGLE = -np.pi/4
# LONGITUDINAL QUANTITIES
ACCEL_MAX = 5 # M / S^2
BRAKE_MAX = 5 # M / S^2
BRAKE_MIN = 1 # M / S^2
JERK_MAX = 2 # M/S^3
BRAKE_ABRUPT = -2.5 # M / S^2
LON_DIST_NORMALIZER = 0.09
# LATERAL QUANTITIES
LAT_DIST_MARGIN = 1 # M    # mu
LAT_ACCEL_MAX = 3.5 # M/S^2
LAT_MIN_BR = 0.7 # M/S^2
LAT_MAX_JERK = 1.5 # M/S^3
LAT_DIST_NORMALIZER = 0.04
# HIGHWAY
HARD_SPEED_LIMIT = 26  # M/S   # 90kph = 25 m/s
SOFT_SPEED_LIMIT = 24  # M/S   # 90kph = 25 m/s
SPEED_LOWER_BOUND = 20
SPEED_LIMIT_TOL = 2.7 # M/S   # 10 kph = 2.77 m/s
POST_ENCROACHMENT = 1.5 # S
LANE_WIDTH = 4  # M
VEHICLE_WIDTH = 2   # M
VEHICLE_LENGTH = 5  # M
TARGET_DISTANCE = 1200
TARGET_DISTANCE_TOL = 50
